# Generated by Django 5.0.2 on 2025-03-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0006_maestros_edad_alter_alumnos_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestros',
            name='materias_json',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
