# Generated by Django 5.0.2 on 2025-03-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0007_alter_maestros_materias_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestros',
            name='materias_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
