# Generated by Django 5.0.2 on 2025-05-11 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0008_alter_maestros_materias_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestros',
            name='materias_json',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
